// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************
// fast mode: true
// **************************************************************************
// ignore_for_file: prefer_const_literals_to_create_immutables,unused_local_variable,unused_import,unnecessary_import,unused_shown_name,implementation_imports,duplicate_import
/// The routeNames auto generated by https://github.com/fluttercandies/ff_annotation_route
const List<String> routeNames = <String>[
  '/',
  '/product',
];

/// The routes auto generated by https://github.com/fluttercandies/ff_annotation_route
class RouteName {
  const RouteName._();

  /// '/'
  ///
  /// [name] : '/'
  ///
  /// [constructors] :
  ///
  /// RootPage : [Key? key]
  static const String root = '/';

  /// '/product'
  ///
  /// [name] : '/product'
  ///
  /// [constructors] :
  ///
  /// ProductPage : [Key? key]
  static const String product = '/product';
}
